source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

project 'DummyTao.xcodeproj'

target 'DummyTao' do
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'JSONModel'
pod 'BaiduMapKit' #百度地图SDK
end
